export const useDepartmentWithSignUp = () => {
  return [
    'ACC - Accounting for HQV',
    'ACS - ATM Cash Section a for HQV',
    'ADM - Office Admin for HQV',
    'AML - Risk Management and Compliance for HQV',
    'AUD - Audit Department for HQV',
    'BRC - Branch Management for HQV',
    'CAC - Customer Account Control Service Center for HQV',
    'COP - Corperate Department for HQV',
    'CPB - Corperate Private for HQV',
    'CRE - Credit Department for HQV',
    'CSC - Card Service Center for HQV',
    'DBS - Digital Banking Section(OPC)',
    'DPS - Deposit Section C Service Center for HQV',
    'EXC - Exchange Section a Service Center for HQV',
    'FCS - Foreign Currency Cash c for HQV',
    'HRD - HR department',
    'IT - IT Center for HQV',
    'ITC - IT Core Banking for HQV',
    'ITE - IT EBanking Section for HQV',
    'LCS - LAO Currency Cash B for HQV',
    'LGS - Legal Section for HQV',
    'LSG - Leasing State Company for HQV',
    'MD - Marketing Director',
    'MKT - Marketing Division for HQV',
    'NOA - New AC Opening a Service Center for HQV',
    'PSS - Products Service Section Service Center for HQV',
    'RND - Research And Develop for HQV',
    'SAL - Salary Transfer a Service Center for HQV',
    'STL - Settle Domestic Bank and Support Account Details Service Center for HQV',
    'TIS - Tisd department for HQV',
    'TRF - Domestic Fund Transfer Service Center for HQV',
    'VIP - VIP Customer Section for HQV',
  ]
}
